apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # labels of deployment resource
  labels:
    # app: nginx
    # tier: frontend
    purpose: helm-deployment
    
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      # app: nginx
      # tier: frontend
      purpose: helm-deployment
      
  template:
    metadata:
      labels:
        # app: nginx
        # tier: frontend
        purpose: helm-deployment
        
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }}
        ports:
        - containerPort: 80